
USE UPHA_DB
GO

CREATE TABLE ESTUDIANTES (
 id_est INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
 nombre VARCHAR(50) NOT NULL,
 matricula  VARCHAR (50) NOT NULL,
 estado BIT NOT NULL
)

CREATE TABLE PROFESORES (
id_prof INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
nombre VARCHAR(50) NOT NULL,
matricula_prof VARCHAR(50) NOT NULL,
estado BIT NOT NULL

)

CREATE TABLE ASIGNATURAS(
id_asig INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
nombre_asignatura VARCHAR(30) NOT NULL,
estado bit NOT NULL
)

CREATE TABLE AULAS(
id_aula INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
numero_aula VARCHAR(30) NOT NULL,
numero_estudiantes INT NULL,
estado BIT NOT NULL
)

CREATE TABLE ASIGNACIONES(
id_asignacion INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
estudiante INT NOT NULL,
profesor INT NOT NULL,
aula INT NOT NULL,
asignatura INT NOT NULL,
estado BIT

CONSTRAINT PK_ID_ESTUDIANTE
FOREIGN KEY (estudiante) 
REFERENCES UPHA_DB..ESTUDIANTES(id_est),

CONSTRAINT PK_ID_PROFESOR
FOREIGN KEY (profesor)
REFERENCES UPHA_DB..PROFESORES(id_prof),

CONSTRAINT PK_ID_ASIGNATURA
FOREIGN KEY (asignatura)
REFERENCES UPHA_DB..ASIGNATURAS(id_asig),

CONSTRAINT PK_ID_AULA
FOREIGN KEY (aula)
REFERENCES UPHA_DB..AULAS(id_aula)
)

INSERT INTO ESTUDIANTES
VALUES
('JOSE MENDEZ','EST-JM-0404',1),
('LUCAS FELIX','EST-LF-0303',1),
('ROSA MARTE','EST-RM-0202',1)

INSERT INTO ASIGNATURAS (nombre_asignatura,estado)
VALUES
('LENGUA ESPAÒOLA',1),
('MATEMATICA',1),
('CIENCIAS SOCIALES',1),
('CIENCIAS NATURALES',1),
('INFORMATICA',1),
('INGLES',1)


INSERT INTO PROFESORES(nombre, matricula_prof,estado)
VALUES
('LUIS SANTOS','PROF-LS-0404',1),
('ANA CRUZ','PROF-AC-0303',1),
('ROSARIO MARTINEZ','PROF-RM-0202',1)


INSERT INTO AULAS (numero_aula,numero_estudiantes,estado)
VALUES
('AU-7845',NULL,1),
('AU-5846',NULL,1),
('AU-4823',NULL,1)




SELECT * FROM ESTUDIANTES
SELECT * FROM PROFESORES
SELECT * FROM AULAS
SELECT * FROM ASIGNACIONES
SELECT * FROM ASIGNATURAS